services:
  web:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    image: php:8.2-fpm
    volumes:
      - ./src:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes: # db_data는 Docker 볼륨으로, MySQL 데이터가 저장됩니다. 
      - db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes: # 이 부분은 Docker 볼륨을 정의합니다.
  db_data:
